version: 2

jobs:
  build:
    working_directory: /OneRepo
    branches:
      only:
        - master
        - devlop
    steps:
      - checkout
      - run:
          name: Update Submodules
          command: |
            apk update
            apk add git
            git submodule init
            git submodule update --remote
      - run:
          name: Install NPM packages
          command: |
            npm install
      - run:
          name: Build Project
          command: |
            npm run build
      - run:
          name: Distribute
          command: |
            curl --user ${CIRCLE_API_TOKEN}: \
                --data build_parameters[CIRCLE_JOB]=$JOB \
                --data build_parameters[BUILD_TAG]=$TAG\
                --data revision=$CIRCLE_SHA1 \
                https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH

  # Start deployment
  dev_deploy:
    machine: true
    working_directory: ~/OneRepo
    steps:
      - add_ssh_keys
      - deploy:
          command: |
            scp -r /home/circleci/repo/OneRepo deployer@STAGING

  deploy:
    machine: true
    working_directory: ~/OneRepo
    steps:
      - add_ssh_keys
      - deploy:
          command: |
            ssh deployer@eggs.se.rit.edu docker service update --image=ritsse/onerepo:$BUILD_TAG sse_web --detach=false
